# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 09:48
from __future__ import unicode_literals

from django.db import migrations, models
import member.models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', member.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('D', 'Django'), ('F', 'Facebook'), ('N', 'Naver')], default='D', max_length=1),
        ),
    ]
