# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 03:33
from __future__ import unicode_literals

from django.db import migrations, models
import utils.fields.custom_imagefield


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='myuser',
            name='nickname',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='profile_image',
            field=utils.fields.custom_imagefield.CustomImageField(blank=True, upload_to='user_profile_img'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='user_type',
            field=models.CharField(choices=[('D', 'Django'), ('F', 'Facebook')], default='F', max_length=1),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
