# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 17:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_auto_20170727_0238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='jibun_address',
            new_name='detail_address',
        ),
    ]
