# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0008_auto_20170731_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
