# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 14:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='exchange_type',
            new_name='trading_type',
        ),
    ]
