# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20170725_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='exchange_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_sold',
            field=models.BooleanField(default=False),
        ),
    ]
