# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 04:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_comment_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postlike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_wishlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
