# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-13 10:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_auto_20170810_1351'),
        ('post', '0009_auto_20170811_1625'),
    ]

    operations = [
    ]
