# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-13 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_comment_html_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='html_content',
            field=models.TextField(blank=True),
        ),
    ]
