# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_post_html_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='for_sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='for_sale_created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
