# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-18 07:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0014_auto_20170818_0148'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='my_posts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_posts', to='post.Post'),
        ),
    ]
