# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-21 05:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0019_auto_20170821_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='my_posts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_posts', to='post.Post'),
        ),
    ]
